In [14]:
from sklearn.preprocessing import OneHotEncoder
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [15]:
# D07 - Adult
df_d07 = pd.read_csv("raw/Adult_dataset.csv")
df_d07.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income,dataset_split
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,train
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,train
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,train
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,train
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,train

---

#### **01 ) - Tratamento dos dados**

- 

---

In [16]:
try:
    _mudar_prefixo_coluna # type: ignore
except NameError:
    _mudar_prefixo_coluna = True

    df_d07_clean = df_d07.copy()
    df_d07_clean = df_d07_clean.rename(columns={'fnlwgt' : 'final_weight'})
    df_d07_clean.columns = [f"{idx}_{col}" for idx, col in enumerate(df_d07_clean.columns, start=1)]

df_d07_clean.head(10)

,1_age,2_workclass,3_final_weight,4_education,5_education_num,6_marital_status,7_occupation,8_relationship,9_race,10_sex,11_capital_gain,12_capital_loss,13_hours_per_week,14_native_country,15_income,16_dataset_split
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,NaN,2174,0,40,United-States,0,train
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,NaN,0,0,13,United-States,0,train
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,NaN,0,0,40,United-States,0,train
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,NaN,0,0,40,United-States,0,train
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,NaN,0,0,40,Cuba,0,train
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,NaN,0,0,40,United-States,0,train
6,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,NaN,0,0,16,Jamaica,0,train
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,NaN,0,0,45,United-States,1,train
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,NaN,14084,0,50,United-States,1,train
9,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,NaN,5178,0,40,United-States,1,train

In [17]:
df_d07_status = pd.read_csv("raw/D07_status.csv")
# df_d07_status['column'] = df_d07_status.columns.tolist()
# df_d07_status.to_csv("raw/D07_status.csv", index=False)
df_d07_status.head(15)

               column transformation  status
0               1_age  Normalization       0
1         2_workclass       CatToNum       0
2      3_final_weight  Normalization       0
3         4_education       CatToNum       0
4     5_education_num  Normalization       0
5    6_marital_status       CatToNum       0
6        7_occupation       CatToNum       0
7      8_relationship       CatToNum       0
8              9_race       CatToNum       0
9              10_sex    CatToBinary       0
10    11_capital_gain  Normalization       0
11    12_capital_loss  Normalization       0
12  13_hours_per_week  Normalization       0
13  14_native_country       CatToNum       0
14          15_income    CatToBinary       0

In [18]:
df_d07_status[df_d07_status['transformation'] == 'CatToNum']['column'].values.tolist()

['2_workclass',
 '4_education',
 '6_marital_status',
 '7_occupation',
 '8_relationship',
 '9_race',
 '14_native_country']

##### 1.1 ) _Transformando variáveis categóricas em binárias_

In [19]:
df_d07_status[df_d07_status['transformation'] == 'CatToBinary']['column']

9        10_sex
14    15_income
Name: column, dtype: str

In [24]:
# Aplicando a transformação na variável "10_sex"
map_sex = {'Male' : 0, 'Female' : 1}
df_d07_clean['10_sex'] = df_d07['sex'].map(map_sex)
df_d07_clean['10_sex'].unique()

array([0, 1])

In [22]:
# Aplicando a transformação na variável "14_income"
map_income = {'<=50K' : 0, '>50K' : 1}
df_d07_clean['15_income'] = df_d07['income'].map(map_income)
df_d07_clean['15_income'].unique()

array([0, 1])

##### 1.2 ) _Transformando variáveis categóricas em numéricas_

In [23]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Creating the encoder
enc = OneHotEncoder(handle_unknown='ignore')

# Sample data
X = [['Red'], ['Green'], ['Blue']]

# Fitting the encoder to the data
enc.fit(X)

# Transforming new data
result = enc.transform([['Red']]).toarray()

# Displaying the encoded result
print(result)

[[0. 0. 1.]]

In [25]:
df_d07_status[df_d07_status['transformation'] == 'CatToNum']['column'].values.tolist()

['2_workclass',
 '4_education',
 '6_marital_status',
 '7_occupation',
 '8_relationship',
 '9_race',
 '14_native_country']